# Generated by Django 5.1.2 on 2025-03-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_app_admin_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Finance', 'Finance'), ('Health', 'Health'), ('Agriculture', 'Agriculture'), ('Trade', 'Trade'), ('Technology', 'Technology'), ('Social Affairs', 'Social Affairs'), ('Justice', 'Justice'), ('Logistics', 'Logistics')], max_length=50),
        ),
    ]
