# Generated by Django 5.1.2 on 2025-11-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_app_content_guidelines_app_regulation_compliance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Platform', 'Platform'), ('Citizen', 'Citizen'), ('Developer', 'Developer')], max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to hide the FAQ without deleting it.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='FAQS with a lower number will appear first.')),
            ],
            options={
                'ordering': ['category', 'display_order', 'question'],
            },
        ),
    ]
