# Generated by Django 5.1.2 on 2025-11-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_faq_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['category', 'question']},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='is_active',
        ),
    ]
